[package]
name = "hoolamike"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/Niedzwiedzw/hoolamike"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.93"
base64 = "0.22.1"
bon = "3.1.1"
chrono = { version = "0.4.38", features = ["serde"] }
clap = { version = "4.5.21", features = ["derive", "cargo", "env"] }
derivative = "2.2.0"
derive_more = { version = "1.0.0", features = ["full"] }
enum-kinds = "0.5.1"
extension-traits = "2.0.0"
futures = "0.3.31"
futures-util = "0.3.31"
itertools = "0.13.0"
num_cpus = "1.16.0"
reqwest = {version = "0.12.9", features = ["stream"]}
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
serde_yaml = "0.9.34"
tabled = "0.17.0"
tap = "1.0.1"
test-log = { version = "0.2.16", default-features = false, features = ["trace"] }
tokio = { version = "1.41.1", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
transpare = { git = "https://github.com/Niedzwiedzw/transpare", version = "0.2.0" }
url = { version = "2.5.4", features = ["serde"] }
xxhash-rust = { version = "0.8.12", features = ["xxh64", "std"] }
