[package]
name = "wrapper-7zip"
version.workspace = true
license.workspace = true
repository.workspace = true
categories.workspace = true
readme.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
base64.workspace = true
binrw.workspace = true
bon.workspace = true
chrono.workspace = true
clap.workspace = true
compress-tools.workspace = true
console.workspace = true
console-subscriber.workspace = true
derivative.workspace = true
derive_more.workspace = true
enum-kinds.workspace = true
enum_dispatch.workspace = true
extension-traits.workspace = true
flate2.workspace = true
fs2.workspace = true
futures.workspace = true
futures-util.workspace = true
hex.workspace = true
indexmap.workspace = true
indicatif.workspace = true
iter-read.workspace = true
itertools.workspace = true
nonempty.workspace = true
num.workspace = true
num_cpus.workspace = true
omnom.workspace = true
once_cell.workspace = true
parking_lot.workspace = true
regex.workspace = true
reqwest.workspace = true
scraper.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_urlencoded.workspace = true
serde_yaml.workspace = true
sevenz-rust.workspace = true
tabled.workspace = true
tap.workspace = true
tempfile.workspace = true
test-log.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
transpare.workspace = true
url.workspace = true
uuid.workspace = true
xxhash-rust.workspace = true
zip.workspace = true
