[package]
name = "hoolamike"
version.workspace = true
license.workspace = true
repository.workspace = true
categories.workspace = true
readme.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
ba2 = { git = "https://github.com/Ryan-rsm-McKenzie/bsa-rs", rev = "b716bcbbf51ec8f7d5e5261128fabfbe3357ddb3" }
# ba2 = { path = "/home/niedzwiedz/Games/modding/bsa-rs" }
base64.workspace = true
binrw.workspace = true
bon.workspace = true
chrono.workspace = true
clap = { workspace = true, features = ["derive", "cargo", "env"] }
compress-tools.workspace = true
console.workspace = true
console-subscriber.workspace = true
crossbeam = { version = "0.8.4", features = ["crossbeam-channel"] }
dashmap = { version = "6.1.0", features = ["inline"] }
derivative.workspace = true
derive_more.workspace = true
enum-kinds.workspace = true
enum_dispatch.workspace = true
extension-traits.workspace = true
flate2.workspace = true
fs2.workspace = true
futures.workspace = true
futures-util.workspace = true
hex.workspace = true
image_dds = { version = "0.6.2", features = ["serde"] }
indexmap.workspace = true
indicatif = { workspace = true, features = ["rayon"] }
iter-read.workspace = true
itertools.workspace = true
memmap2 = "0.9.5"
nonempty.workspace = true
normalize-path = "0.2.1"
num.workspace = true
num_cpus.workspace = true
omnom.workspace = true
once_cell.workspace = true
os_pipe = "1.2.1"
parking_lot.workspace = true
rand = "0.8.5"
rayon = "1.10.0"
regex.workspace = true
reqwest.workspace = true
ringbuffer = "0.15.0"
scraper.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_urlencoded.workspace = true
serde_yaml.workspace = true
sevenz-rust.workspace = true
static_assertions = { version = "1.1.0", features = ["nightly"] }
tabled.workspace = true
tap.workspace = true
tempfile.workspace = true
test-log.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-indicatif = "0.3.8"
tracing-subscriber.workspace = true
transpare.workspace = true
url.workspace = true
uuid.workspace = true
wrapped-7zip.workspace = true
xxhash-rust.workspace = true
zip.workspace = true
